apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-application
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: garadsnehal98/first-ci-cd:12345
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker-login-secret
